### ISSUE TITLE
pandas_sum_average_multiple_workbooks.py

### ISSUE THREAD

**Issue by Chengjingsilent** [cbrownley/foundations-for-analytics-with-python#7]
I copied this code, but it couldn't run on my computer with showing: 
Traceback (most recent call last):
  File "pandas_sum_average_multiple_workbooks.py", line 32, in <module>
    worksheet_data_frames.append(pd.DataFrame(data, columns=['workbook', 'worksheet', 'worksheet_total', 'worksheet_average']))
  File "D:\Applications\Anaconda\lib\site-packages\pandas\core\frame.py", line 392, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "D:\Applications\Anaconda\lib\site-packages\pandas\core\internals\construction.py", line 212, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "D:\Applications\Anaconda\lib\site-packages\pandas\core\internals\construction.py", line 56, in arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "D:\Applications\Anaconda\lib\site-packages\pandas\core\internals\construction.py", line 277, in _homogenize
    raise_cast_failure=False)
  File "D:\Applications\Anaconda\lib\site-packages\pandas\core\internals\construction.py", line 660, in sanitize_array
    subarr = com.asarray_tuplesafe(data, dtype=dtype)
  File "D:\Applications\Anaconda\lib\site-packages\pandas\core\common.py", line 240, in asarray_tuplesafe
    values = [tuple(x) for x in values]
  File "D:\Applications\Anaconda\lib\site-packages\pandas\core\common.py", line 240, in <listcomp>
    values = [tuple(x) for x in values]
TypeError: 'int' object is not iterable

**Comment by nardinmarcus** [comment]
hello world

**Comment by XinYunke6ke4** [comment]
I have the same question

**Comment by caoweiyi2580** [comment]
I have something wrong with the same line as well. 
But the error is:
ValueError: Data must be 1-dimensional

**Comment by sian1989** [comment]
I have the same erorr as ValueError: Data must be 1-dimensional

**Comment by xiaohongguoer** [comment]
您好，邮件我已收到，Best wish for you！

**Comment by sian1989** [comment]
> I copied this code, but it couldn't run on my computer with showing: Traceback (most recent call last): File "pandas_sum_average_multiple_workbooks.py", line 32, in worksheet_data_frames.append(pd.DataFrame(data, columns=['workbook', 'worksheet', 'worksheet_total', 'worksheet_average'])) File "D:\Applications\Anaconda\lib\site-packages\pandas\core\frame.py", line 392, in **init** mgr = init_dict(data, index, columns, dtype=dtype) File "D:\Applications\Anaconda\lib\site-packages\pandas\core\internals\construction.py", line 212, in init_dict return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype) File "D:\Applications\Anaconda\lib\site-packages\pandas\core\internals\construction.py", line 56, in arrays_to_mgr arrays = _homogenize(arrays, index, dtype) File "D:\Applications\Anaconda\lib\site-packages\pandas\core\internals\construction.py", line 277, in _homogenize raise_cast_failure=False) File "D:\Applications\Anaconda\lib\site-packages\pandas\core\internals\construction.py", line 660, in sanitize_array subarr = com.asarray_tuplesafe(data, dtype=dtype) File "D:\Applications\Anaconda\lib\site-packages\pandas\core\common.py", line 240, in asarray_tuplesafe values = [tuple(x) for x in values] File "D:\Applications\Anaconda\lib\site-packages\pandas\core\common.py", line 240, in values = [tuple(x) for x in values] TypeError: 'int' object is not iterable

Here are the correct one: https://blog.csdn.net/cici2013/article/details/86705172

**Comment by NNNightglow** [comment]
Here are the new correct one: https://blog.csdn.net/NNNightglow/article/details/133563881?spm=1001.2014.3001.5502

**Comment by xiaohongguoer** [comment]
您好，邮件我已收到，Best wish for you！
